name: CI/CD Pipeline for Swag Labs Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python (for Selenium-based tests)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Selenium tests and generate Allure results
      - name: Run tests with Selenium
        run: |
          pytest --alluredir=allure-results

      # Step 5: Generate Allure report
      - name: Generate Allure report
        run: |
          pip install allure-pytest
          allure generate allure-results -o allure-report --clean

      # Step 6: Upload the Allure report as an artifact
      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
